language: android
jdk: oraclejdk8

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

android:
  components:
    - tools
    - platform-tools
    - build-tools-29.0.3
    - android-29
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
before_script:
  - chmod +x gradlew
script:
  - ./gradlew build

after_success:
  - ./gradlew javadocRelease

deploy:
  provider: pages:git
  token: $GITHUB_TOKEN
  edge: true
  keep_history: true
  local_dir: dynamic-motion/build/docs/javadoc/release
  on:
    all_branches: true
    tags: true
