language: android
jdk: oraclejdk8
sudo: required

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
licenses:
  - '.+'
before_script:
  - chmod +x gradlew
script:
  - ./gradlew build

after_success:
  - ./gradlew javadocRelease

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dynamic-motion/build/docs/javadoc/release
  on:
    branch: master